#!/bin/bash

set -e

v=5.2.0
basedir="$(cd $(dirname $0); pwd)"
cd "$basedir"

if [[ ! -d flyway-$v ]]
then
    rm -f flyway-$v.zip
    wget https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/$v/flyway-commandline-$v.zip
    unzip -q flyway-commandline-$v.zip
fi

exec flyway-$v/flyway "$@"
