#!/bin/bash

set -e
set -x

if [[ ! -d env ]]
then
    virtualenv -p python3 env
fi

env/bin/pip install -e web
env/bin/pip install -r requirements.txt

export FLASK_APP=p2k16_web.server
export FLASK_DEBUG=1
export P2K16_CONFIG=`pwd`/web/config-test.cfg

env/bin/pytest

