#!/bin/bash

set -e
set -x

basedir=$(cd $(dirname $0); pwd)

if [[ ! -d env ]]
then
    virtualenv -p python3 env
fi

env/bin/pip install --trusted-host github.com -e web --process-dependency-links

./flyway migrate

cd web
bower install
cd ..

export FLASK_APP=p2k16.web.server
export FLASK_DEBUG=1
export P2K16_CONFIG=$basedir/infrastructure/config-local.cfg

# Use the Stripe non-prod API
export WEBHOOK_SECRET='test'
export STRIPE_SECRET_KEY='sk_test_JgaPEgWXlT6VkmLcz0bcIkOf'
export STRIPE_PUBLIC_KEY='pk_test_hUoh3MEu4Oa8RjVFwZrFge4b'

#exec env/bin/flask run
exec env/bin/gunicorn -b 127.0.0.1:5000 p2k16.web:app
