#!/bin/bash

set -e
set -x

if [[ ! -d env ]]
then
    virtualenv -p python3 env
fi

env/bin/pip install -e web

cd web
bower install
cd ..

export FLASK_APP=p2k16_web.server
export FLASK_DEBUG=1
export P2K16_CONFIG=`pwd`/config-local.cfg
exec env/bin/flask run
