#!/bin/bash

set -e
set -x

if [[ ! -d env ]]
then
    virtualenv -p python3 env
fi

env/bin/pip install -e web --process-dependency-links
env/bin/pip install -r requirements.txt

export FLASK_APP=p2k16_web.server
export FLASK_DEBUG=1
export P2K16_CONFIG=`pwd`/web/config-test.cfg
export WEBHOOK_SECRET='test'
export STRIPE_SECRET_KEY='sk_test_JgaPEgWXlT6VkmLcz0bcIkOf'
export STRIPE_PUBLIC_KEY='pk_test_hUoh3MEu4Oa8RjVFwZrFge4b'

env/bin/pytest
