#!/bin/bash

set -ex pipefail

basedir="$(cd $(dirname $0); pwd)"

if [[ ! -d env ]]
then
    virtualenv -p python3 env
fi

env/bin/pip install -e web --process-dependency-links
env/bin/pip install -r requirements.txt

./flyway migrate

export FLASK_APP=p2k16.web.server
export FLASK_DEBUG=1
export P2K16_CONFIG=$basedir/infrastructure/config-it.cfg

# Use the Stripe non-prod API
export STRIPE_WEBHOOK_SECRET='whsec_Rr4aEG6kaZWIljjybZxqibta4Yjkakna'
export STRIPE_SECRET_KEY='sk_test_JgaPEgWXlT6VkmLcz0bcIkOf'
export STRIPE_PUBLIC_KEY='pk_test_hUoh3MEu4Oa8RjVFwZrFge4b'

exec env/bin/pytest \
    --log-level DEBUG \
    --log-format "%(asctime)s %(name)-40s %(levelname)s %(message)s" \
    --log-date-format "%Y-%m-%d %H:%M:%S" \
     -r apP \
    | tee test.log
