#!/bin/bash

ssh bomba.bitraf.no 'cat - > p2k12-export.psql' <<EOF
\copy auth to '/tmp/p2k12_auth.csv' with csv header
\copy members to '/tmp/p2k12_members.csv' with csv header
\copy accounts to '/tmp/p2k12_accounts.csv' with csv header
\copy checkins to '/tmp/p2k12_checkins.csv' with csv header
\copy stripe_customer to '/tmp/p2k12_stripe_customer.csv' with csv header
\copy stripe_payment to '/tmp/p2k12_stripe_payment.csv' with csv header
EOF

ssh -t bomba.bitraf.no sudo -u postgres psql -d p2k12 -f p2k12-export.psql

scp bomba.bitraf.no:/tmp/*.csv p2k12/
