#!/bin/bash

if [ -r /etc/p2k16/flyway.conf ]
then
  pw=$(sed -n "s,^flyway.password=\(.*\),\1,p" /etc/p2k16/flyway.conf)
else
  pw=p2k16-flyway
fi

psql "user=p2k16-flyway password=$pw dbname=p2k16 host=localhost" \
    -1 \
    -f $(dirname $0)/import.sql
