#!/bin/bash

set -euo pipefail

basedir=/opt/p2k16

cd "$basedir"

mkdir -p log
export P2K16_LOGGING=src/infrastructure/logging-file.yaml

exec env/bin/gunicorn \
    --config src/infrastructure/gunicorn-config.py \
    p2k16.web.server:app
