#!/bin/bash

set -euo pipefail

basedir=/opt/p2k16/src

export P2K16_LOGGING=$basedir/infrastructure/logging.yaml

exec env/bin/gunicorn \
    --config $basedir/infrastructure/gunicorn-config.py \
    p2k16.web.server:app
