#!/bin/sh

set -eu

tools=$(dirname "$0")
basedir=$(dirname "$tools")

set -x
v=7.0.2

cd "$tools"
if [ ! -d "flyway-$v" ]
then
  rm -f "flyway-$v.zip"
  wget "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/$v/flyway-commandline-$v.zip"
  unzip -q "flyway-commandline-$v.zip"
  chmod +x flyway-$v/flyway
fi

cd -

exec "$tools/flyway-$v/flyway" \
  "-configFiles=$tools/flyway.conf" \
   "${@}"
