#!/bin/sh

set -eu

tools=$(dirname "$0")
basedir=$(dirname "$tools")

set -x
v=7.0.2

cd "$tools"
if [ ! -d "flyway-$v" ]
then
  url="https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/$v/flyway-commandline-$v.zip"
  rm -f "flyway-$v.zip"
  if command -v wget &> /dev/null; then
    wget "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/$v/flyway-commandline-$v.zip"
  elif command -v curl &> /dev/null; then
    curl -LO $url
  else
    echo "Neither curl nor wget found?"
    exit 1
  fi
  unzip -q "flyway-commandline-$v.zip"
  chmod +x flyway-$v/flyway
fi

cd -

exec "$tools/flyway-$v/flyway" \
  "-configFiles=$tools/flyway.conf" \
   "${@}"
