#!/bin/bash

set -e
set -x

tools=$(dirname "$0")
basedir=$(dirname "$tools")

if [[ ! -d env ]]
then
    virtualenv -p python3 env
fi

env/bin/pip install -r requirements.txt
env/bin/pip install -e web

flyway migrate

cd web
bower install
cd ..

export FLASK_DEBUG=1
export P2K16_CONFIG=$basedir/infrastructure/config-local.cfg
export P2K16_LOGGING=$basedir/infrastructure/logging-stdout.yaml

# Use the Stripe non-prod API
export STRIPE_WEBHOOK_SECRET='whsec_Rr4aEG6kaZWIljjybZxqibta4Yjkakna'
export STRIPE_SECRET_KEY='sk_test_JgaPEgWXlT6VkmLcz0bcIkOf'
export STRIPE_PUBLIC_KEY='pk_test_hUoh3MEu4Oa8RjVFwZrFge4b'

exec env/bin/gunicorn \
    --config "$basedir/infrastructure/gunicorn-config.py" \
    --reload \
    p2k16.web.server:app
