#!/bin/bash

export PYTHONPATH=.
export FLASK_APP=p2k16_web.server
export FLASK_DEBUG=1
export P2K16_CONFIG=`pwd`/config-local.cfg

if [[ ! -d env ]]
then
    virtualenv -p python3 env
fi

env/bin/pip install -r requirements.txt

exec env/bin/flask run
